GET http://localhost:2000/pokemon
###
POST http://localhost:2000/pokemon HTTP/1.1
content-type: application/json

{
   "name": "squirtle",
        "type": "water",
        "generation": "1",
        "region": "kanto",
        "finalEvolution": "blastoise",
        "item": "shiny stone",
        "moves": [
            "water gun",
            "headbutt",
            "bubble"

        ]
}
###
GET http://localhost:2000/trainers

### Render
GET https://cse341-project2-xjcc.onrender.com/pokemon

POST https://cse341-project2-xjcc.onrender.com/pokemon HTTP/1.1
Content-Type: application/json

{
   "name": "charmander",
        "type": "fire",
        "generation": "1",
        "region": "kanto",
        "finalEvolution": "charizard",
        "item": "charcoal",
        "moves": [
            "ember",
            "bite",
            "tackle"

        ]
}